name: fizz-buzz

services:
  webapp:
    container_name: webapp
    image: ${DOCKER_IMAGE:-webapp}:${DOCKER_TAG:-latest}
    profiles: [prod]
    environment:
      VITE_DEBUG: ${VITE_DEBUG:?error}
      VITE_NAME: ${VITE_NAME:?error}
      VITE_DESCRIPTION: ${VITE_DESCRIPTION:?error}
      VITE_DEV_PORT: ${VITE_DEV_PORT:?error}
      VITE_PREVIEW_PORT: ${VITE_PREVIEW_PORT:?error}
      VITE_HTTP_PORT: ${VITE_HTTP_PORT:?error}
      VITE_HTTPS_PORT: ${VITE_HTTPS_PORT:?error}
      VITE_SSL_CERT_PATH: ${VITE_SSL_CERT_PATH:?error}
      VITE_SSL_KEY_PATH: ${VITE_SSL_KEY_PATH:?error}
    # noinspection ComposeUnknownValues
    ports:
      - ${VITE_HTTP_PORT:?error}:${VITE_HTTP_PORT:?error}
      - ${VITE_HTTPS_PORT:?error}:${VITE_HTTPS_PORT:?error}
    restart: unless-stopped
    tty: true
    volumes:
      - ${VITE_SSL_CERT_PATH:?error}:${VITE_SSL_CERT_PATH:?error}
      - ${VITE_SSL_KEY_PATH:?error}:${VITE_SSL_KEY_PATH:?error}
      - nginx-data:/var/log/nginx

  webapp-healthcheck:
    container_name: webapp-healthcheck
    image: alpine
    profiles: [prod]
    restart: no
    depends_on:
      webapp:
        condition: service_healthy
    command: ["sh", "-c", "echo 'All services are healthy, exiting.'"]

volumes:
  nginx-data:
    external: true
    name: ${DOCKER_IMAGE:-webapp}-nginx-data
