name: fizz-buzz

services:
  webapp:
    container_name: webapp
    image: ${DOCKER_IMAGE:-${DEFAULT_DOCKER_IMAGE:-webapp}}:${DOCKER_TAG:-latest}
    profiles: [prod]
    environment:
      _WEBAPP_DEBUG: ${_WEBAPP_DEBUG:?error}
      _WEBAPP_HTTP_PORT: ${_WEBAPP_HTTP_PORT:?error}
      _WEBAPP_HTTPS_PORT: ${_WEBAPP_HTTPS_PORT:?error}
      RETINA_WEBAPP_VIEW: ${RETINA_WEBAPP_VIEW:?error}
      RETINA_WEBAPP_API_URL: ${RETINA_WEBAPP_API_URL:?error}
      _WEBAPP_SSL_CERT_PATH: ${_WEBAPP_SSL_CERT_PATH:?error}
      _WEBAPP_SSL_KEY_PATH: ${_WEBAPP_SSL_KEY_PATH:?error}
    # noinspection ComposeUnknownValues
    ports:
      - ${_WEBAPP_HTTP_PORT:?error}:${_WEBAPP_HTTP_PORT:?error}
      - ${_WEBAPP_HTTPS_PORT:?error}:${_WEBAPP_HTTPS_PORT:?error}
    restart: unless-stopped
    tty: true
    volumes:
      - ${_WEBAPP_SSL_CERT_PATH:?error}:${_WEBAPP_SSL_CERT_PATH:?error}
      - ${_WEBAPP_SSL_KEY_PATH:?error}:${_WEBAPP_SSL_KEY_PATH:?error}
      - nginx-data:/var/log/nginx

  webapp-healthcheck:
    container_name: webapp-healthcheck
    image: alpine
    profiles: [prod]
    restart: no
    depends_on:
      webapp:
        condition: service_healthy
    command: ["sh", "-c", "echo 'All services are healthy, exiting.'"]

volumes:
  nginx-data:
    external: true
    name: webapp-nginx-data
